# Generated by Django 3.2 on 2021-09-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='order_id',
            field=models.CharField(default='failed', max_length=100),
        ),
    ]
