# Generated by Django 3.2 on 2021-09-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='productDesc',
            field=models.CharField(default="It's a good product truly", max_length=500),
        ),
    ]
