# Generated by Django 3.2 on 2021-09-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_productdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='productImage',
            field=models.FileField(blank=True, default='uploads/products/skillengineering.jpg', null=True, upload_to='uploads/products'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
