# Generated by Django 3.2 on 2021-09-22 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_auto_20210921_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deposite',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='post',
            name='subscriptionPeriod',
            field=models.IntegerField(choices=[(3, 3), (6, 6), (12, 12), (24, 24)], default=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default='I yet to set up my profile!', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
