# Generated by Django 3.2 on 2021-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210922_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
