# Generated by Django 3.2 on 2021-10-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emailId',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phoneNo',
            field=models.BigIntegerField(default=0),
        ),
    ]
